### ISSUE TITLE
error 'instance' is inaccessible due to 'internal' protection level 

### ISSUE THREAD

**Issue by greatsk55** [intmain/HairPowder#2]
import UIKit
import HairPowder

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        HairPowder.instance.spread()
        return true
    }
}

HairPowder.instance.spread() -> error 'instance' is inaccessible due to 'internal' protection level 

so i try 'HairPowder.spread()' instead of HairPowder.instance.spread() but it was Similar error

**Comment by intmain** [comment]
Thanks for report the issue. 

fixxed that to public. 

Thank you.

**Comment by prdpsingh402** [comment]
You can create a singleton class in a framework like this. Please make the public Class and public static getInstance function.
         
          public class ClassName {
           
          // Singleton instance
           private static var instance         : ClassName?
          
          /********* Singleton Instance ****************
          public static func getInstance() -> ClassName {
                   if (instance != nil) {
                       return instance!
                    }
                 // Initialize instance.
                 instance = ClassName()
                 return instance!
            }
        }
